version: 1
commands:
  package:
    - mkdir -p dist
    - mercury luabundle
    - cp dist/optic.lua package/lua-global/optic.lua
    - rm -f dist/optic.lua
    - cp -R data/ package/lua-data-global/optic
    - mercury pack package/ dist/
    - rm -rf package/lua-data-global/optic
    - rm -f package/lua-global/optic.lua
  release:
    - mercury build package